#!/usr/bin/env sh
# Code samples must be runnable as published, and links must resolve for a
# reader who arrived from a search result. Run from the repository root:
#
#   sh scripts/check-extraction-hostile-markdown.sh
#
# An agent or a person who copies a shell sample out of these docs runs it as
# written. A sample that uses a variable it never sets fails on the first line,
# and the reader cannot tell whether they are missing a step or the sample is
# wrong. The same goes for a heading anchor that no longer matches its heading.
# This checks the three classes we have actually shipped:
#
#   1. undefined shell variable: a bash, sh or shell code fence uses $NAME
#      without assigning NAME anywhere in the same fence.
#   2. raw i18n token: a translation placeholder such as {locale} or a General
#      Translation component such as <GTProvider> left in published markdown.
#   3. escaped link target: a backslash inside a link target, which is a
#      markdown escape that survived into the URL and does not resolve.
#
# One class was checked for and dropped. A link anchor containing a literal +,
# such as #persistent-profiles-with-scrape-+-interact, looks like an escaping
# artefact and is not one: the rendered heading on
# https://docs.firecrawl.dev/features/interact carries exactly that id, and a +
# in a URL fragment is not decoded as a space. Flagging it would fail a working
# link, so it is not flagged.
#
# Only the English tree is checked. The localized trees are regenerated by the
# translation pipeline, so a finding there is fixed in the pipeline or the
# English source, never by hand editing a localized file.
#
# FIRECRAWL_API_KEY is the one variable a sample may use without setting it:
# it is the reader's own credential and every sample expects it in the
# environment. Bare placeholders that are not shell variables, such as
# SCRAPE_ID in a URL path or fc-YOUR_API_KEY in a header, are not flagged.
set -eu

locales='^(es|fr|ja|pt-BR|zh)/|^snippets/(es|fr|ja|pt-BR|zh)/'

# Variables a sample may use without assigning it in the same fence.
allow_vars='FIRECRAWL_API_KEY'

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT INT TERM

git ls-files '*.mdx' | grep -Ev "$locales" >"$work/english-mdx"

status=0

# 1. Undefined shell variables inside shell code fences.
xargs awk -v allow="$allow_vars" '
  function flush() {
    for (i = 1; i <= nuses; i++) {
      name = use_name[i]
      if (name in assigned) continue
      if (name in allowed) continue
      if (name ~ /^[0-9]+$/) continue
      if (name in special) continue
      key = FILENAME "\t" name
      if (reported[key]++) continue
      print "undefined shell variable: " FILENAME ":" use_line[i] " uses $" name " and never sets it"
    }
    delete assigned
    nuses = 0
  }
  BEGIN {
    n = split(allow, a, ",")
    for (i = 1; i <= n; i++) allowed[a[i]] = 1
    split("HOME PATH PWD OLDPWD USER LOGNAME SHELL TERM TMPDIR LANG RANDOM SECONDS IFS PS1 PS2 PS4 LINENO FUNCNAME OSTYPE HOSTNAME HOSTTYPE MACHTYPE EDITOR PAGER SHLVL UID EUID PPID BASH BASH_SOURCE BASH_VERSION BASHPID REPLY", s, " ")
    for (i in s) special[s[i]] = 1
  }
  FNR == 1 { if (fenced) flush(); fenced = 0 }
  /^[[:space:]]*(```|~~~)/ {
    if (fenced) { flush(); fenced = 0; next }
    info = $0
    sub(/^[[:space:]]*(```|~~~)/, "", info)
    fenced = (tolower(info) ~ /(^|[^a-z])(bash|sh|shell|zsh|console|curl)([^a-z]|$)/)
    nuses = 0
    delete assigned
    next
  }
  !fenced { next }
  {
    line = $0

    # Assignments: NAME=..., export NAME=..., for NAME in, read NAME,
    # while read NAME, and NAME in a shell function argument list.
    rest = line
    while (match(rest, /(^|[;&|(){}[:space:]])(export[[:space:]]+|local[[:space:]]+|declare[[:space:]]+|readonly[[:space:]]+)?[A-Za-z_][A-Za-z0-9_]*=/)) {
      frag = substr(rest, RSTART, RLENGTH)
      if (match(frag, /[A-Za-z_][A-Za-z0-9_]*=$/)) {
        name = substr(frag, RSTART, RLENGTH - 1)
        assigned[name] = 1
      }
      rest = substr(rest, RSTART + RLENGTH)
    }
    # `for NAME in`, and `read` with any flags and any number of names, which
    # is how a pipeline names the fields of each line it reads.
    rest = line
    while (match(rest, /(^|[;&|[:space:]])(for|read)[[:space:]]/)) {
      rest = substr(rest, RSTART + RLENGTH - 1)
      tail = rest
      if (match(tail, /[;|&]/)) tail = substr(tail, 1, RSTART - 1)
      while (match(tail, /[A-Za-z_-][A-Za-z0-9_-]*/)) {
        name = substr(tail, RSTART, RLENGTH)
        tail = substr(tail, RSTART + RLENGTH)
        if (name ~ /^-/) continue
        if (name == "in" || name == "do") break
        assigned[name] = 1
      }
    }

    # Uses: $NAME and ${NAME...}. A backslash before the $ escapes it, and
    # $$ is the process id, so both are skipped.
    rest = line
    pos = 0
    while (match(rest, /\$\{?[A-Za-z_][A-Za-z0-9_]*/)) {
      before = (RSTART > 1) ? substr(rest, RSTART - 1, 1) : ((pos > 0) ? prevchar : "")
      frag = substr(rest, RSTART, RLENGTH)
      sub(/^\$\{?/, "", frag)
      if (before != "\\" && before != "$") {
        nuses++
        use_name[nuses] = frag
        use_line[nuses] = FNR
      }
      prevchar = substr(rest, RSTART + RLENGTH - 1, 1)
      pos = 1
      rest = substr(rest, RSTART + RLENGTH)
    }
  }
  END { if (fenced) flush() }
' <"$work/english-mdx" >"$work/undefined-vars" || true

# 2. Raw i18n tokens.
xargs grep -noE '\{locale\}|\[locale\]|\[locales\]|</?GTProvider|<Var[[:space:]>]|<Branch[[:space:]>]|<Plural[[:space:]>]' \
  <"$work/english-mdx" 2>/dev/null |
  sed 's/^/raw i18n token: /' >"$work/i18n-tokens" || true

# 3. Escaped link targets: a backslash that survived into a link URL.
xargs grep -noE '\]\([^)]*\\[^)]*\)' <"$work/english-mdx" 2>/dev/null |
  sed 's/^/escaped link target: /' >"$work/anchors" || true

for report in undefined-vars i18n-tokens anchors; do
  if [ -s "$work/$report" ]; then
    cat "$work/$report" >&2
    status=1
  fi
done

if [ "$status" -ne 0 ]; then
  echo "Published samples must run as written and links must resolve." >&2
  exit 1
fi

echo "Extraction-hostile markdown checks passed."
